import { Dimensions } from 'react-native';

const SWIPE_VELOCITY_THRESHOLD = 0.2;
const DIRECTION_OFFSET_THRESHOLD = 80;
const GESTURE_IS_CLICK_THRESHOLD = 10;
const NOT_SCROLL_THRESHOLD = 300;
const SCROLL_RATIO_THRESHOLD = 0.75;
const HOLD_THRESHOLD = 500;

const SCREEN_WIDTH = Dimensions.get('window').width;
const SCREEN_HEIGHT = Dimensions.get('window').height;
const SWIPE_THRESHOLD = SCREEN_WIDTH / 4;
const SWIPE_RATIO_THRESHOLD = 5;
const MOVE_THRESHOLD = 10;

export {
  SWIPE_VELOCITY_THRESHOLD,
  DIRECTION_OFFSET_THRESHOLD,
  GESTURE_IS_CLICK_THRESHOLD,
  NOT_SCROLL_THRESHOLD,
  SCROLL_RATIO_THRESHOLD,
  HOLD_THRESHOLD,
  SCREEN_WIDTH,
  SCREEN_HEIGHT,
  SWIPE_THRESHOLD,
  SWIPE_RATIO_THRESHOLD,
  MOVE_THRESHOLD
}; 
